### ISSUE TITLE
Update to accept access token param

### ISSUE THREAD

**Issue by enchorb** [fastlane/fastlane-plugin-firebase_app_distribution#274]
Can the following line in `firebase_app_distribution_action.rb` be updated in the next version of this plugin.
I have this working locally and in our CI/CD, as we obtain an access token through WLIF (workload identity federation) and service account impersonation and pass in the access token as a param directly 
 
```
auth_token = params[:access_token] || fetch_auth_token(
          params[:service_credentials_file], params[:firebase_cli_token], params[:debug]
        )
```

**Comment by mannyjimenez0810** [comment]
Hello @enchorb Thanks for reaching out about this. Could you tell me more about your use case? Is there some reason that the ```params[:service_credentials_file]``` doesn't work for you?

**Comment by enchorb** [comment]
Hey, that works just fine but the reason for this is so we don't need to store any long-lived credentials like service accounts.

In CI/CD we use WLIF (workload identity federation) which is then able to impersonate a service account to get an access token which is then added to the `.env` that Fastlane and by extension this plugin would read the access token from

**Comment by mannyjimenez0810** [comment]
Hey, are you able to use the ```GOOGLE_APPLICATION_CREDENTIALS``` environmental variable to authenticate? We already [support](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/b2dd465d20f739edef9f66093298c425525f2c9a/lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_auth_client.rb#L35) Application Default Credentials which is used in WIF. Does that work for your use case?

**Comment by enchorb** [comment]
Hey @lfkellogg `GOOGLE_APPLICATION_CREDENTIALS` does not carry over jobs/workflows in CI/CD, a more common use case is to pass an impersonated access token through the app as a variable as so: 

```
     - name: Authenticate To Google Cloud
        if: github.event_name == 'push'
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          access_token_lifetime: 300s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          workload_identity_provider: projects/${{ steps.environment.outputs.gcp_num }}/locations/global/workloadIdentityPools/gh-${{ github.event.repository.name }}-pool/providers/gh-${{ github.event.repository.name }}-provider
          service_account: gh-${{ github.event.repository.name }}-runner@${{ steps.environment.outputs.gcp_id }}.iam.gserviceaccount.com

      - name: Impersonate Deployment Account
        if: github.event_name == 'push'
        id: auth
        run: |-
          echo "::set-output name=access_token::$(gcloud auth print-access-token --impersonate-service-account='${{ env.SERVICE_ACCOUNT }}@${{ steps.environment.outputs.gcp_id }}.iam.gserviceaccount.com')"
```
